#Diabetes prediction

#import libraries

In [334]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

#Import Dataset

In [335]:
df = pd.read_csv("https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv")

In [336]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [337]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [338]:
df.describe ()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

#Define columns

In [339]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [340]:
df.shape

(768, 9)

#Get x standardize

In [341]:
from sklearn.preprocessing import MinMaxScaler

In [342]:
mm = MinMaxScaler()

In [343]:
 x = mm.fit_transform (x)

In [344]:
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

#Define y(output) and x(input)

In [345]:
y=df['diabetes']

In [346]:
y.shape

(768,)

In [311]:
x=df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

In [347]:
x = df.drop('diabetes', axis = 1)

In [348]:
x.shape

(768, 8)

#Train Test Split

In [349]:
from sklearn.model_selection import train_test_split

In [350]:
x_train, x_test, y_train, y_test=train_test_split(x, y, random_state=2529)

#Get model train

In [351]:
from sklearn.linear_model import LogisticRegression

In [352]:
model = LogisticRegression()

In [353]:
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#predict model

In [354]:
y_pred=model.predict(x_test)

In [355]:
y_pred.shape

(192,)

In [356]:
y_pred

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

#Get probablity of each predicted class

In [357]:
model.predict_proba(x_test)

array([[0.92418069, 0.07581931],
       [0.54095608, 0.45904392],
       [0.17415809, 0.82584191],
       [0.61415121, 0.38584879],
       [0.67692081, 0.32307919],
       [0.3081985 , 0.6918015 ],
       [0.04238317, 0.95761683],
       [0.17235677, 0.82764323],
       [0.97635885, 0.02364115],
       [0.53879036, 0.46120964],
       [0.97173808, 0.02826192],
       [0.10444156, 0.89555844],
       [0.8548153 , 0.1451847 ],
       [0.96513476, 0.03486524],
       [0.85360854, 0.14639146],
       [0.35520851, 0.64479149],
       [0.32044927, 0.67955073],
       [0.55896706, 0.44103294],
       [0.96188603, 0.03811397],
       [0.8789072 , 0.1210928 ],
       [0.43406792, 0.56593208],
       [0.49864068, 0.50135932],
       [0.77088353, 0.22911647],
       [0.98021802, 0.01978198],
       [0.81328721, 0.18671279],
       [0.85612507, 0.14387493],
       [0.78075054, 0.21924946],
       [0.50056894, 0.49943106],
       [0.94891568, 0.05108432],
       [0.75106617, 0.24893383],
       [0.

#Get model Evaluation

In [358]:
from sklearn.metrics import confusion_matrix, classification_report

In [359]:
print(confusion_matrix(y_test,y_pred))

[[108  10]
 [ 33  41]]


In [360]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.92      0.83       118
           1       0.80      0.55      0.66        74

    accuracy                           0.78       192
   macro avg       0.78      0.73      0.74       192
weighted avg       0.78      0.78      0.77       192



#Get future prediction


1.Extract a random row using a sample function

2.seprate x and y

3.Standardize x

4.predict

In [361]:
x_new = df.sample(1)

In [362]:
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
118            4       97         60       23        0  28.2  0.443   22   

     diabetes  
118         0

In [363]:
x_new.shape

(1, 9)

In [364]:
x_new = x_new.drop('diabetes', axis=1)

In [330]:
x_new = mm.fit_transform(x_new)

In [365]:
y_pred_new = model.predict(x_new)

In [366]:
y_pred_new

array([0])

In [367]:
model.predict_proba(x_new)

array([[0.8991283, 0.1008717]])